// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgulsqczrahxzjziexku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndWxzcWN6cmFoeHpqemlleGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTM3NzIsImV4cCI6MjA1NzAyOTc3Mn0.PMzCGd9Ojunwa_SDov1O692RMmAMaHfYXotfw3HpFPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);